On Linux, reuse the index compiler as the build compiler, and use wrappers.
 * Many current Linux distributions lack a C++11 toolchain, such as the
   current stable release of Debian (6.0) and the latest CentOS (6.3).  I
   would like to support these distributions.

 * SourceWeb needs Clang 3.2 to index code, and Clang 3.2 is a suitable
   C++11 compiler.

 * It is convenient to reuse the indexing compiler as the build compiler,
   so this patch makes that the default configuration on Linux.

 * The Clang 3.2 compiler still needs a 4.6 or a 4.7 libstdc++ library.
   By default, Clang is configured to look at both the host system and its
   install directory for the newest libstdc++.  With the packages I created
   at the clang-redist-linux GitHub project, it is easy to build SourceWeb
   by extracting the clang-3.2 and gcc-libs-4.6 packages into a single
   tree, then passing that tree's path to configure.

 * Once SourceWeb is built, it will require a new enough libstdc++ at
   run-time.  This is handled by replacing the executables with wrapper
   scripts that examine the host system's libstdc++ and a wrapped
   executable.  If the wrapped executable needs a newer libstdc++ than the
   one on the host system, the LD_LIBRARY_PATH variable is set pointing to
   the --with-clang-dir directory.

   This solution deals with situations like:
    - The --with-clang-dir directory contains libstdc++-4.6, but the host
      system has libstdc++-4.7.  Clang is expected to link SourceWeb
      programs against the 4.7 library, so we must not use the 4.6 library
      at run-time.
    - The --with-clang-dir directory contains libstdc++-4.6.  The user
      upgrades their distribution from libstdc++-4.4 to libstdc++-4.7.  By
      delaying the libstdc++ override decision to run-time, we ensure that
      the older 4.6 library is no longer used.  (While the SourceWeb
      binaries should be OK with 4.6, the navigator links with the host's
      Qt libraries, which might require 4.7 on a 4.7 distribution.)

 * The real executables (and libbtrace shared object) are now in the
   libexec directory.  The wrapper scripts need to find the libexec
   directory, so I removed the configurable --bindir option.

 * Unrelated: Try to make libbtrace/btrace.sh safe for paths containing
   spaces.  I think such paths still break most parts of the project.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -11,7 +11,6 @@ Configures SourceWeb and runs qmake to generate makefiles.
 
 Installation directories:
   --prefix=PREFIX         Base path for build/install.  Default: /usr/local
-  --bindir=BINDIR         Directory for binaries.  Default: PREFIX/bin
 
 Dependency options:
   --with-clang-dir=CLANG_DIR
@@ -25,24 +24,30 @@ EOF
 while [ $# -gt 0 ]; do
     ARG=$1
     case $ARG in
-        --prefix|--bindir|--with-clang-dir)
+        --prefix|--with-clang-dir)
             shift
             ARG=$ARG=$1
     esac
     case $ARG in
         --prefix=*) PREFIX=${ARG#*=}; shift;;
-        --bindir=*) BINDIR=${ARG#*=}; shift;;
         --with-clang-dir=*) CLANG_DIR=${ARG#*=}; shift;;
         -h|--help) usage; exit 0;;
-        *) echo "error: Unrecognized argument $ARG"; exit 1;;
+        *) echo "$0: error: Unrecognized argument $ARG"; exit 1;;
     esac
 done
 
 PREFIX=${PREFIX:-/usr/local}
-BINDIR=${BINDIR:-$PREFIX/bin}
 
 if [ "$CLANG_DIR" = "" ]; then
-    echo "error: A Clang $CLANG_VER directory must be specified using --with-clang-dir."
+    echo "$0: error: A Clang $CLANG_VER directory must be specified using --with-clang-dir."
+    exit 1
+fi
+if [ "${CLANG_DIR#/}" = "$CLANG_DIR" ]; then
+    echo "$0: error: --with-clang-dir path must be absolute."
+    exit 1
+fi
+if [ "${PREFIX#/}" = "$PREFIX" ]; then
+    echo "$0: error: --prefix path must be absolute."
     exit 1
 fi
 
@@ -70,19 +75,31 @@ else
     fi
 fi
 
+QMAKE_FLAGS=""
+
+
+################################################################################
+# On Linux, build the project using the same Clang compiler used to index code.
+# Many current Linux distributions lack a C++11 toolchain, so reusing the
+# indexing compiler is convenient.
+
+if [ "$(uname)" = "Linux" ]; then
+    # Ideally, we would also change the spec file to unsupported/linux-clang
+    # on Linux, but that spec file does not exist in Qt 4.6, which many current
+    # distributions still use.
+    QMAKE_FLAGS="$QMAKE_FLAGS QMAKE_CC=$CLANG_DIR/bin/clang"
+    QMAKE_FLAGS="$QMAKE_FLAGS QMAKE_CXX=$CLANG_DIR/bin/clang++"
+    QMAKE_FLAGS="$QMAKE_FLAGS QMAKE_LINK=$CLANG_DIR/bin/clang++"
+fi
+
 
 ################################################################################
 # By default, qmake on OS X generates an Xcode project file.  We need it to
 # generate a Makefile instead, so provide a spec file unless QMAKESPEC is set.
 
-OSX_SPEC_ARG=""
-if [ "$QMAKESPEC" = "" ]; then
-    case $(uname) in
-        Darwin)
-            echo "The default qmake spec is not suitable.  Overriding it."
-            OSX_SPEC_ARG="-spec unsupported/macx-clang"
-            ;;
-    esac
+if [ "$(uname)" = "Darwin" -a "$QMAKESPEC" = "" ]; then
+    echo "The default qmake spec is not suitable.  Overriding it."
+    QMAKE_FLAGS="$QMAKE_FLAGS -spec unsupported/macx-clang"
 fi
 
 
@@ -97,7 +114,7 @@ run_test()
 
 # Test that the qmake configuration is working and has sufficient C++11 support.
 echo "Testing C++11 support using $QMAKE..."
-run_test "$SRCDIR/cxx11-compat-test/run-test.sh" "$QMAKE" $OSX_SPEC_ARG
+run_test "$SRCDIR/cxx11-compat-test/run-test.sh" "$QMAKE" $QMAKE_FLAGS
 if [ $? -ne 0 ]; then
     echo "- Command failed.  Output of $PWD/cxx11-compat-test.log:"
     while read LINE; do
@@ -117,8 +134,8 @@ run_qmake()
     "$@"
 }
 
-run_qmake "$QMAKE" -r "$SRCDIR/sourceweb.pro" $OSX_SPEC_ARG \
-    PREFIX="$PREFIX" BINDIR="$BINDIR" CLANG_DIR="$CLANG_DIR"
+run_qmake "$QMAKE" -r "$SRCDIR/sourceweb.pro" $QMAKE_FLAGS \
+    PREFIX="$PREFIX" CLANG_DIR="$CLANG_DIR"
 if [ $? -ne 0 ]; then
     echo qmake failed
     exit 1
